import type {
  CoreExercise,
  CoreExerciseVariant,
} from '@/infrastructure/db/models/core-exercise.types';
import type { CoreMuscleGroup } from '@/infrastructure/db/models/core-muscle-group.types';

type SeedMuscleGroup = Omit<CoreMuscleGroup, '_id' | 'createdAt' | 'updatedAt'>;
type SeedExerciseVariant = Omit<CoreExerciseVariant, '_id'>;
type SeedExercise = Omit<CoreExercise, '_id' | 'createdAt' | 'updatedAt' | 'variants'> & {
  variants: SeedExerciseVariant[];
};

export const exerciseAtlasMuscleGroups: SeedMuscleGroup[] = [
  {
    name: 'Chest',
    slug: 'chest',
    parentGroupId: null,
    level: 0,
    category: 'upper_body',
    aliases: ['Pectorals', 'Pecs'],
    description: 'Primary pushing muscles of the upper torso.',
    isTrackableVolume: true,
    order: 10,
  },
  {
    name: 'Pectorals',
    slug: 'pectorals',
    parentGroupId: 'chest',
    level: 1,
    category: 'upper_body',
    aliases: ['Chest'],
    description: 'Main horizontal and incline pressing prime movers.',
    isTrackableVolume: true,
    order: 11,
  },
  {
    name: 'Back',
    slug: 'back',
    parentGroupId: null,
    level: 0,
    category: 'upper_body',
    aliases: ['Upper Back'],
    description: 'Primary pulling muscles of the torso.',
    isTrackableVolume: true,
    order: 20,
  },
  {
    name: 'Latissimus Dorsi',
    slug: 'lats',
    parentGroupId: 'back',
    level: 1,
    category: 'upper_body',
    aliases: ['Lats'],
    description: 'Main vertical and diagonal pulling muscles.',
    isTrackableVolume: true,
    order: 21,
  },
  {
    name: 'Trapezius and Rhomboids',
    slug: 'upper-back',
    parentGroupId: 'back',
    level: 1,
    category: 'upper_body',
    aliases: ['Traps', 'Rhomboids'],
    description: 'Scapular retractors and stabilizers used in rows and carries.',
    isTrackableVolume: true,
    order: 22,
  },
  {
    name: 'Shoulders',
    slug: 'shoulders',
    parentGroupId: null,
    level: 0,
    category: 'upper_body',
    aliases: ['Delts', 'Deltoids'],
    description: 'Primary muscles for pressing, raising, and stabilizing the arms.',
    isTrackableVolume: true,
    order: 30,
  },
  {
    name: 'Anterior and Lateral Deltoids',
    slug: 'front-side-delts',
    parentGroupId: 'shoulders',
    level: 1,
    category: 'upper_body',
    aliases: ['Front Delts', 'Side Delts'],
    description: 'Common prime movers in presses and lateral raises.',
    isTrackableVolume: true,
    order: 31,
  },
  {
    name: 'Posterior Deltoids',
    slug: 'rear-delts',
    parentGroupId: 'shoulders',
    level: 1,
    category: 'upper_body',
    aliases: ['Rear Delts'],
    description: 'Shoulder extensors active during rows and reverse fly patterns.',
    isTrackableVolume: true,
    order: 32,
  },
  {
    name: 'Arms',
    slug: 'arms',
    parentGroupId: null,
    level: 0,
    category: 'upper_body',
    aliases: ['Upper Arms'],
    description: 'Elbow flexors and extensors used in isolation and compound lifts.',
    isTrackableVolume: true,
    order: 40,
  },
  {
    name: 'Biceps',
    slug: 'biceps',
    parentGroupId: 'arms',
    level: 1,
    category: 'upper_body',
    aliases: ['Biceps Brachii'],
    description: 'Elbow flexors used in curls and pulling movements.',
    isTrackableVolume: true,
    order: 41,
  },
  {
    name: 'Triceps',
    slug: 'triceps',
    parentGroupId: 'arms',
    level: 1,
    category: 'upper_body',
    aliases: ['Triceps Brachii'],
    description: 'Elbow extensors used in pressing and extension patterns.',
    isTrackableVolume: true,
    order: 42,
  },
  {
    name: 'Core',
    slug: 'core',
    parentGroupId: null,
    level: 0,
    category: 'core',
    aliases: ['Abdominals', 'Midsection'],
    description: 'Trunk flexors, stabilizers, and rotators.',
    isTrackableVolume: true,
    order: 50,
  },
  {
    name: 'Rectus Abdominis and Transverse Abdominis',
    slug: 'abs',
    parentGroupId: 'core',
    level: 1,
    category: 'core',
    aliases: ['Abs'],
    description: 'Anterior trunk muscles used in bracing and anti-extension.',
    isTrackableVolume: true,
    order: 51,
  },
  {
    name: 'Obliques',
    slug: 'obliques',
    parentGroupId: 'core',
    level: 1,
    category: 'core',
    aliases: ['External Obliques', 'Internal Obliques'],
    description: 'Rotational and anti-rotational trunk muscles.',
    isTrackableVolume: true,
    order: 52,
  },
  {
    name: 'Lower Body',
    slug: 'lower-body',
    parentGroupId: null,
    level: 0,
    category: 'lower_body',
    aliases: ['Legs', 'Hips'],
    description: 'Primary locomotive and lower-body strength muscles.',
    isTrackableVolume: true,
    order: 60,
  },
  {
    name: 'Quadriceps',
    slug: 'quadriceps',
    parentGroupId: 'lower-body',
    level: 1,
    category: 'lower_body',
    aliases: ['Quads'],
    description: 'Knee extensors used in squats, lunges, and leg presses.',
    isTrackableVolume: true,
    order: 61,
  },
  {
    name: 'Hamstrings',
    slug: 'hamstrings',
    parentGroupId: 'lower-body',
    level: 1,
    category: 'lower_body',
    aliases: ['Posterior Thigh'],
    description: 'Hip extensors and knee flexors active in hinge patterns.',
    isTrackableVolume: true,
    order: 62,
  },
  {
    name: 'Glutes',
    slug: 'glutes',
    parentGroupId: 'lower-body',
    level: 1,
    category: 'lower_body',
    aliases: ['Gluteus Maximus', 'Gluteus Medius'],
    description: 'Primary hip extensors and stabilizers.',
    isTrackableVolume: true,
    order: 63,
  },
  {
    name: 'Adductors',
    slug: 'adductors',
    parentGroupId: 'lower-body',
    level: 1,
    category: 'lower_body',
    aliases: ['Inner Thigh'],
    description: 'Hip adductors supporting squat and lunge patterns.',
    isTrackableVolume: true,
    order: 64,
  },
  {
    name: 'Calves and Shins',
    slug: 'calves-shins',
    parentGroupId: 'lower-body',
    level: 1,
    category: 'lower_body',
    aliases: ['Lower Leg'],
    description: 'Ankle plantar flexors and dorsiflexors.',
    isTrackableVolume: true,
    order: 65,
  },
  {
    name: 'Full Body',
    slug: 'full-body',
    parentGroupId: null,
    level: 0,
    category: 'full_body',
    aliases: ['Integrated'],
    description: 'Integrated movement category for total-body exercises.',
    isTrackableVolume: false,
    order: 70,
  },
];

export const exerciseAtlasExercises: SeedExercise[] = [
  {
    name: 'Bench Press',
    slug: 'bench-press',
    aliases: ['Flat Bench Press'],
    type: 'compound',
    movementPattern: 'push',
    difficulty: 'beginner',
    muscles: [
      { muscleGroupId: 'pectorals', role: 'primary', activationLevel: 0.95 },
      { muscleGroupId: 'triceps', role: 'secondary', activationLevel: 0.72 },
      {
        muscleGroupId: 'front-side-delts',
        role: 'secondary',
        activationLevel: 0.65,
      },
    ],
    description: 'Horizontal pressing pattern for upper-body strength and hypertrophy.',
    instructions: [
      'Set the upper back and feet before unracking.',
      'Lower the bar or handles under control to the torso.',
      'Press up while maintaining a stable ribcage and shoulder position.',
    ],
    tips: ['Keep forearms stacked under the load.', 'Use a consistent touch point.'],
    commonMistakes: ['Flaring elbows excessively.', 'Losing leg drive and upper-back tension.'],
    variants: [
      {
        name: 'Barbell Bench Press',
        slug: 'barbell-bench-press',
        equipment: ['barbell', 'bench'],
        gripOptions: ['pronated', 'wide', 'narrow', 'shoulder_width'],
        bodyPosition: 'lying_flat',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Dumbbell Bench Press',
        slug: 'dumbbell-bench-press',
        equipment: ['dumbbell', 'bench'],
        gripOptions: ['pronated', 'neutral'],
        bodyPosition: 'lying_flat',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
      {
        name: 'Smith Machine Bench Press',
        slug: 'smith-machine-bench-press',
        equipment: ['smith_machine', 'bench'],
        gripOptions: ['pronated', 'shoulder_width'],
        bodyPosition: 'lying_flat',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['strength', 'hypertrophy', 'chest'],
    goals: ['strength', 'hypertrophy'],
    isActive: true,
  },
  {
    name: 'Incline Bench Press',
    slug: 'incline-bench-press',
    aliases: ['Incline Press'],
    type: 'compound',
    movementPattern: 'push',
    difficulty: 'intermediate',
    muscles: [
      { muscleGroupId: 'pectorals', role: 'primary', activationLevel: 0.9 },
      {
        muscleGroupId: 'front-side-delts',
        role: 'secondary',
        activationLevel: 0.78,
      },
      { muscleGroupId: 'triceps', role: 'secondary', activationLevel: 0.7 },
    ],
    description: 'Upper-chest pressing variation performed on an incline bench.',
    variants: [
      {
        name: 'Barbell Incline Bench Press',
        slug: 'barbell-incline-bench-press',
        equipment: ['barbell', 'bench'],
        gripOptions: ['pronated', 'shoulder_width'],
        bodyPosition: 'incline',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Dumbbell Incline Bench Press',
        slug: 'dumbbell-incline-bench-press',
        equipment: ['dumbbell', 'bench'],
        gripOptions: ['pronated', 'neutral'],
        bodyPosition: 'incline',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['hypertrophy', 'chest', 'shoulders'],
    goals: ['strength', 'hypertrophy'],
    isActive: true,
  },
  {
    name: 'Overhead Press',
    slug: 'overhead-press',
    aliases: ['Shoulder Press'],
    type: 'compound',
    movementPattern: 'push',
    difficulty: 'intermediate',
    muscles: [
      {
        muscleGroupId: 'front-side-delts',
        role: 'primary',
        activationLevel: 0.92,
      },
      { muscleGroupId: 'triceps', role: 'secondary', activationLevel: 0.74 },
      { muscleGroupId: 'abs', role: 'stabilizer', activationLevel: 0.48 },
    ],
    description: 'Vertical pressing pattern performed standing or seated.',
    variants: [
      {
        name: 'Barbell Overhead Press',
        slug: 'barbell-overhead-press',
        equipment: ['barbell'],
        gripOptions: ['pronated', 'shoulder_width'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Dumbbell Shoulder Press',
        slug: 'dumbbell-shoulder-press',
        equipment: ['dumbbell', 'bench'],
        gripOptions: ['pronated', 'neutral'],
        bodyPosition: 'seated',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['strength', 'shoulders'],
    goals: ['strength', 'hypertrophy'],
    isActive: true,
  },
  {
    name: 'Lateral Raise',
    slug: 'lateral-raise',
    type: 'isolation',
    movementPattern: 'other',
    difficulty: 'beginner',
    muscles: [
      {
        muscleGroupId: 'front-side-delts',
        role: 'primary',
        activationLevel: 0.9,
      },
      { muscleGroupId: 'upper-back', role: 'stabilizer', activationLevel: 0.35 },
    ],
    description: 'Isolation movement for shoulder abduction and deltoid hypertrophy.',
    variants: [
      {
        name: 'Dumbbell Lateral Raise',
        slug: 'dumbbell-lateral-raise',
        equipment: ['dumbbell'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Cable Lateral Raise',
        slug: 'cable-lateral-raise',
        equipment: ['cable'],
        attachmentOptions: ['single_handle'],
        bodyPosition: 'standing',
        limbMode: 'unilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['hypertrophy', 'shoulders'],
    goals: ['hypertrophy'],
    isActive: true,
  },
  {
    name: 'Pull-Up',
    slug: 'pull-up',
    aliases: ['Chin-Up Family'],
    type: 'compound',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    muscles: [
      { muscleGroupId: 'lats', role: 'primary', activationLevel: 0.94 },
      { muscleGroupId: 'biceps', role: 'secondary', activationLevel: 0.68 },
      { muscleGroupId: 'upper-back', role: 'secondary', activationLevel: 0.58 },
    ],
    description: 'Vertical pulling pattern using bodyweight or assisted loading.',
    variants: [
      {
        name: 'Bodyweight Pull-Up',
        slug: 'bodyweight-pull-up',
        equipment: ['bodyweight', 'pull_up_bar'],
        gripOptions: ['pronated', 'supinated', 'neutral', 'wide', 'narrow'],
        bodyPosition: 'hanging',
        limbMode: 'bilateral',
        trackableMetrics: ['reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Assisted Pull-Up',
        slug: 'assisted-pull-up',
        equipment: ['machine', 'pull_up_bar'],
        gripOptions: ['pronated', 'neutral', 'supinated'],
        bodyPosition: 'hanging',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['back', 'bodyweight'],
    goals: ['strength', 'hypertrophy'],
    isActive: true,
  },
  {
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    type: 'compound',
    movementPattern: 'pull',
    difficulty: 'beginner',
    muscles: [
      { muscleGroupId: 'lats', role: 'primary', activationLevel: 0.92 },
      { muscleGroupId: 'biceps', role: 'secondary', activationLevel: 0.6 },
      { muscleGroupId: 'upper-back', role: 'secondary', activationLevel: 0.52 },
    ],
    description: 'Machine or cable vertical pull for lats and upper back.',
    variants: [
      {
        name: 'Wide-Grip Lat Pulldown',
        slug: 'wide-grip-lat-pulldown',
        equipment: ['cable'],
        gripOptions: ['pronated', 'wide'],
        attachmentOptions: ['lat_bar'],
        bodyPosition: 'seated',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Neutral-Grip Lat Pulldown',
        slug: 'neutral-grip-lat-pulldown',
        equipment: ['cable'],
        gripOptions: ['neutral'],
        attachmentOptions: ['v_bar', 'double_handle'],
        bodyPosition: 'seated',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['back', 'lats'],
    goals: ['hypertrophy', 'strength'],
    isActive: true,
  },
  {
    name: 'Row',
    slug: 'row',
    aliases: ['Horizontal Row'],
    type: 'compound',
    movementPattern: 'pull',
    difficulty: 'beginner',
    muscles: [
      { muscleGroupId: 'upper-back', role: 'primary', activationLevel: 0.88 },
      { muscleGroupId: 'lats', role: 'secondary', activationLevel: 0.77 },
      { muscleGroupId: 'rear-delts', role: 'secondary', activationLevel: 0.63 },
      { muscleGroupId: 'biceps', role: 'secondary', activationLevel: 0.55 },
    ],
    description: 'Horizontal pulling family for upper back, lats, and rear delts.',
    variants: [
      {
        name: 'Barbell Bent-Over Row',
        slug: 'barbell-bent-over-row',
        equipment: ['barbell'],
        gripOptions: ['pronated', 'supinated', 'shoulder_width'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Single-Arm Dumbbell Row',
        slug: 'single-arm-dumbbell-row',
        equipment: ['dumbbell', 'bench'],
        bodyPosition: 'standing',
        limbMode: 'unilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
      {
        name: 'Seated Cable Row',
        slug: 'seated-cable-row',
        equipment: ['cable'],
        attachmentOptions: ['v_bar', 'straight_bar', 'double_handle'],
        bodyPosition: 'seated',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['back', 'hypertrophy'],
    goals: ['strength', 'hypertrophy'],
    isActive: true,
  },
  {
    name: 'Back Squat',
    slug: 'back-squat',
    aliases: ['Squat'],
    type: 'compound',
    movementPattern: 'squat',
    difficulty: 'intermediate',
    muscles: [
      { muscleGroupId: 'quadriceps', role: 'primary', activationLevel: 0.9 },
      { muscleGroupId: 'glutes', role: 'secondary', activationLevel: 0.82 },
      { muscleGroupId: 'adductors', role: 'secondary', activationLevel: 0.52 },
      { muscleGroupId: 'abs', role: 'stabilizer', activationLevel: 0.48 },
    ],
    description: 'Foundational bilateral squat pattern for lower-body strength.',
    variants: [
      {
        name: 'Barbell Back Squat',
        slug: 'barbell-back-squat',
        equipment: ['barbell'],
        stanceOptions: ['narrow', 'shoulder_width', 'wide', 'sumo'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Smith Machine Squat',
        slug: 'smith-machine-squat',
        equipment: ['smith_machine'],
        stanceOptions: ['narrow', 'shoulder_width', 'wide'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['legs', 'strength'],
    goals: ['strength', 'hypertrophy'],
    isActive: true,
  },
  {
    name: 'Leg Press',
    slug: 'leg-press',
    type: 'compound',
    movementPattern: 'squat',
    difficulty: 'beginner',
    muscles: [
      { muscleGroupId: 'quadriceps', role: 'primary', activationLevel: 0.9 },
      { muscleGroupId: 'glutes', role: 'secondary', activationLevel: 0.68 },
      { muscleGroupId: 'adductors', role: 'secondary', activationLevel: 0.4 },
    ],
    description: 'Machine squat pattern with high lower-body loading potential.',
    variants: [
      {
        name: '45-Degree Leg Press',
        slug: '45-degree-leg-press',
        equipment: ['machine'],
        stanceOptions: ['narrow', 'shoulder_width', 'wide'],
        bodyPosition: 'seated',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
    ],
    tags: ['legs', 'machine'],
    goals: ['hypertrophy', 'strength'],
    isActive: true,
  },
  {
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    aliases: ['RDL'],
    type: 'compound',
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    muscles: [
      { muscleGroupId: 'hamstrings', role: 'primary', activationLevel: 0.92 },
      { muscleGroupId: 'glutes', role: 'secondary', activationLevel: 0.84 },
      { muscleGroupId: 'abs', role: 'stabilizer', activationLevel: 0.4 },
    ],
    description: 'Hip hinge focused on posterior-chain lengthened loading.',
    variants: [
      {
        name: 'Barbell Romanian Deadlift',
        slug: 'barbell-romanian-deadlift',
        equipment: ['barbell'],
        gripOptions: ['pronated', 'mixed'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Dumbbell Romanian Deadlift',
        slug: 'dumbbell-romanian-deadlift',
        equipment: ['dumbbell'],
        gripOptions: ['neutral'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['posterior-chain', 'hamstrings'],
    goals: ['strength', 'hypertrophy'],
    isActive: true,
  },
  {
    name: 'Conventional Deadlift',
    slug: 'conventional-deadlift',
    aliases: ['Deadlift'],
    type: 'compound',
    movementPattern: 'hinge',
    difficulty: 'advanced',
    muscles: [
      { muscleGroupId: 'glutes', role: 'primary', activationLevel: 0.9 },
      { muscleGroupId: 'hamstrings', role: 'secondary', activationLevel: 0.78 },
      { muscleGroupId: 'upper-back', role: 'secondary', activationLevel: 0.65 },
      { muscleGroupId: 'abs', role: 'stabilizer', activationLevel: 0.54 },
    ],
    description: 'Heavy floor-based hinge for total-body strength development.',
    variants: [
      {
        name: 'Barbell Conventional Deadlift',
        slug: 'barbell-conventional-deadlift',
        equipment: ['barbell'],
        gripOptions: ['pronated', 'mixed'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Trap Bar Deadlift',
        slug: 'trap-bar-deadlift',
        equipment: ['trap_bar'],
        gripOptions: ['neutral'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['strength', 'posterior-chain'],
    goals: ['strength'],
    isActive: true,
  },
  {
    name: 'Lunge',
    slug: 'lunge',
    type: 'compound',
    movementPattern: 'lunge',
    difficulty: 'beginner',
    muscles: [
      { muscleGroupId: 'quadriceps', role: 'primary', activationLevel: 0.84 },
      { muscleGroupId: 'glutes', role: 'secondary', activationLevel: 0.8 },
      { muscleGroupId: 'adductors', role: 'secondary', activationLevel: 0.45 },
      { muscleGroupId: 'abs', role: 'stabilizer', activationLevel: 0.42 },
    ],
    description: 'Unilateral lower-body pattern for strength, balance, and hypertrophy.',
    variants: [
      {
        name: 'Walking Lunge',
        slug: 'walking-lunge',
        equipment: ['bodyweight'],
        stanceOptions: ['split_stance', 'staggered'],
        bodyPosition: 'standing',
        limbMode: 'alternating',
        trackableMetrics: ['reps', 'distance', 'rpe'],
        isDefault: true,
      },
      {
        name: 'Dumbbell Reverse Lunge',
        slug: 'dumbbell-reverse-lunge',
        equipment: ['dumbbell'],
        stanceOptions: ['split_stance', 'staggered'],
        bodyPosition: 'standing',
        limbMode: 'alternating',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['legs', 'unilateral'],
    goals: ['hypertrophy', 'endurance'],
    isActive: true,
  },
  {
    name: 'Hip Thrust',
    slug: 'hip-thrust',
    type: 'compound',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    muscles: [
      { muscleGroupId: 'glutes', role: 'primary', activationLevel: 0.95 },
      { muscleGroupId: 'hamstrings', role: 'secondary', activationLevel: 0.48 },
      { muscleGroupId: 'abs', role: 'stabilizer', activationLevel: 0.32 },
    ],
    description: 'Hip-dominant glute exercise performed from a bench-supported setup.',
    variants: [
      {
        name: 'Barbell Hip Thrust',
        slug: 'barbell-hip-thrust',
        equipment: ['barbell', 'bench'],
        bodyPosition: 'lying_flat',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Dumbbell Hip Thrust',
        slug: 'dumbbell-hip-thrust',
        equipment: ['dumbbell', 'bench'],
        bodyPosition: 'lying_flat',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['glutes', 'hypertrophy'],
    goals: ['hypertrophy', 'strength'],
    isActive: true,
  },
  {
    name: 'Leg Curl',
    slug: 'leg-curl',
    type: 'isolation',
    movementPattern: 'hinge',
    difficulty: 'beginner',
    muscles: [
      { muscleGroupId: 'hamstrings', role: 'primary', activationLevel: 0.92 },
      { muscleGroupId: 'glutes', role: 'stabilizer', activationLevel: 0.28 },
    ],
    description: 'Knee flexion isolation for hamstring development.',
    variants: [
      {
        name: 'Seated Leg Curl',
        slug: 'seated-leg-curl',
        equipment: ['machine'],
        bodyPosition: 'seated',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Lying Leg Curl',
        slug: 'lying-leg-curl',
        equipment: ['machine'],
        bodyPosition: 'lying_flat',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['hamstrings', 'machine'],
    goals: ['hypertrophy', 'rehab'],
    isActive: true,
  },
  {
    name: 'Calf Raise',
    slug: 'calf-raise',
    type: 'isolation',
    movementPattern: 'other',
    difficulty: 'beginner',
    muscles: [
      {
        muscleGroupId: 'calves-shins',
        role: 'primary',
        activationLevel: 0.94,
      },
    ],
    description: 'Ankle plantar-flexion movement for lower-leg development.',
    variants: [
      {
        name: 'Standing Calf Raise',
        slug: 'standing-calf-raise',
        equipment: ['machine'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Seated Calf Raise',
        slug: 'seated-calf-raise',
        equipment: ['machine'],
        bodyPosition: 'seated',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['calves'],
    goals: ['hypertrophy'],
    isActive: true,
  },
  {
    name: 'Biceps Curl',
    slug: 'biceps-curl',
    aliases: ['Curl'],
    type: 'isolation',
    movementPattern: 'pull',
    difficulty: 'beginner',
    muscles: [{ muscleGroupId: 'biceps', role: 'primary', activationLevel: 0.95 }],
    description: 'Direct elbow-flexion movement for biceps growth.',
    variants: [
      {
        name: 'Dumbbell Curl',
        slug: 'dumbbell-curl',
        equipment: ['dumbbell'],
        gripOptions: ['supinated', 'neutral'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'EZ-Bar Curl',
        slug: 'ez-bar-curl',
        equipment: ['ez_bar'],
        gripOptions: ['supinated', 'narrow', 'shoulder_width'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
      {
        name: 'Cable Curl',
        slug: 'cable-curl',
        equipment: ['cable'],
        attachmentOptions: ['straight_bar', 'ez_bar', 'rope'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['arms'],
    goals: ['hypertrophy'],
    isActive: true,
  },
  {
    name: 'Triceps Pushdown',
    slug: 'triceps-pushdown',
    aliases: ['Cable Pushdown'],
    type: 'isolation',
    movementPattern: 'push',
    difficulty: 'beginner',
    muscles: [{ muscleGroupId: 'triceps', role: 'primary', activationLevel: 0.95 }],
    description: 'Cable elbow-extension movement for triceps development.',
    variants: [
      {
        name: 'Rope Triceps Pushdown',
        slug: 'rope-triceps-pushdown',
        equipment: ['cable'],
        attachmentOptions: ['rope'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
        isDefault: true,
      },
      {
        name: 'Straight-Bar Triceps Pushdown',
        slug: 'straight-bar-triceps-pushdown',
        equipment: ['cable'],
        attachmentOptions: ['straight_bar', 'ez_bar', 'v_bar'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe', 'rir'],
      },
    ],
    tags: ['arms'],
    goals: ['hypertrophy'],
    isActive: true,
  },
  {
    name: 'Plank',
    slug: 'plank',
    type: 'isolation',
    movementPattern: 'other',
    difficulty: 'beginner',
    muscles: [
      { muscleGroupId: 'abs', role: 'primary', activationLevel: 0.88 },
      { muscleGroupId: 'obliques', role: 'secondary', activationLevel: 0.62 },
      { muscleGroupId: 'glutes', role: 'stabilizer', activationLevel: 0.28 },
    ],
    description: 'Anti-extension trunk stability exercise.',
    variants: [
      {
        name: 'Forearm Plank',
        slug: 'forearm-plank',
        equipment: ['bodyweight'],
        bodyPosition: 'lying_flat',
        limbMode: 'bilateral',
        trackableMetrics: ['duration', 'rpe'],
        isDefault: true,
      },
      {
        name: 'Weighted Plank',
        slug: 'weighted-plank',
        equipment: ['bodyweight', 'other'],
        bodyPosition: 'lying_flat',
        limbMode: 'bilateral',
        trackableMetrics: ['duration', 'weight', 'rpe'],
      },
    ],
    tags: ['core'],
    goals: ['endurance', 'rehab'],
    isActive: true,
  },
  {
    name: 'Cable Wood Chop',
    slug: 'cable-wood-chop',
    aliases: ['Wood Chop'],
    type: 'compound',
    movementPattern: 'rotation',
    difficulty: 'intermediate',
    muscles: [
      { muscleGroupId: 'obliques', role: 'primary', activationLevel: 0.9 },
      { muscleGroupId: 'abs', role: 'secondary', activationLevel: 0.58 },
      { muscleGroupId: 'full-body', role: 'stabilizer', activationLevel: 0.3 },
    ],
    description: 'Rotational trunk pattern for obliques and integrated power control.',
    variants: [
      {
        name: 'High-to-Low Cable Wood Chop',
        slug: 'high-to-low-cable-wood-chop',
        equipment: ['cable'],
        attachmentOptions: ['single_handle'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe'],
        isDefault: true,
      },
      {
        name: 'Low-to-High Cable Wood Chop',
        slug: 'low-to-high-cable-wood-chop',
        equipment: ['cable'],
        attachmentOptions: ['single_handle'],
        bodyPosition: 'standing',
        limbMode: 'bilateral',
        trackableMetrics: ['weight', 'reps', 'rpe'],
      },
    ],
    tags: ['core', 'rotation'],
    goals: ['endurance', 'rehab'],
    isActive: true,
  },
];
